### ISSUE TITLE
[Question] NPM name

### ISSUE THREAD

**Issue by jaysalvat** [jprichardson/buzz#8]
Hello!

I'm the author of the Buzz audio library created in 2011 +1000 Github stars.
https://github.com/jaysalvat/buzz

By popular demand, I would like to publish it on NPM. Unfortunately the NPM Buzz name is already taken and most of users are confused (My lib has the Buzz name on Bower for years).

Your library seems to not have been updated for 3 years. So would you be kind enough to consider renaming your NPM project and give the NPM Buzz name to the Buzz audio community ?

**Comment by jprichardson** [comment]
@jaysalvat I actually actively use my cli utility `buzz`, but I'm not attached to the name, so sure. What's your npm user name?

**Comment by jaysalvat** [comment]
Great, thanks a lot!

My npm name is `jaysalvat`

Thanks again.

**Comment by jaysalvat** [comment]
Please keep me informed and tell me if I can help.

Thanks again.

**Comment by jprichardson** [comment]
Done. Added you as owner. Feel free to publish over my `buzz`.

**Comment by jaysalvat** [comment]
Published. 
Thanks you very much JP!
